name: mf_data_extraction
channels:
    - conda-forge
    - defaults
    - bioconda
dependencies:
    - geopandas
    - flopy
    - numpy
    - pandas
    - pip
    - pyarrow
    - snakemake
    - py7zr
    - pyshp
    - pip:
        - sciencebasepy
